import 'package:flutter/material.dart';

/// Fixed Material icon map for category `iconKey` (web + mobile stable).
final Map<String, IconData> kOnboardingCategoryIconMap = <String, IconData>{
  'lock': Icons.lock_outline,
  'savings': Icons.savings_outlined,
  'home': Icons.home_outlined,
  'work': Icons.work_outline,
  'restaurant': Icons.restaurant_outlined,
  'directions_car': Icons.directions_car_outlined,
  'shopping_cart': Icons.shopping_cart_outlined,
  'movie': Icons.movie_outlined,
  'fitness': Icons.fitness_center_outlined,
  'pets_outline': Icons.pets_outlined,
  'school': Icons.school_outlined,
  'local_hospital': Icons.local_hospital_outlined,
  'flight': Icons.flight_outlined,
  'category': Icons.category_outlined,
  'account_balance': Icons.account_balance_outlined,
  'attach_money': Icons.attach_money_outlined,
  'bakery_dining': Icons.bakery_dining_outlined,
  'beach_access': Icons.beach_access_outlined,
  'bolt': Icons.bolt_outlined,
  'brush': Icons.brush_outlined,
  'build': Icons.build_outlined,
  'cake': Icons.cake_outlined,
  'call': Icons.call_outlined,
  'camera': Icons.camera_alt_outlined,
  'card_giftcard': Icons.card_giftcard_outlined,
  'celebration': Icons.celebration_outlined,
  'chair': Icons.chair_outlined,
  'child_care': Icons.child_care_outlined,
  'cleaning_services': Icons.cleaning_services_outlined,
  'coffee': Icons.coffee_outlined,
  'computer': Icons.computer_outlined,
  'credit_card': Icons.credit_card_outlined,
  'diamond': Icons.diamond_outlined,
  'directions_bus': Icons.directions_bus_outlined,
  'dry_cleaning': Icons.dry_cleaning_outlined,
  'electric_bolt': Icons.electric_bolt_outlined,
  'emoji_events': Icons.emoji_events_outlined,
  'emoji_food_beverage': Icons.emoji_food_beverage_outlined,
  'ev_station': Icons.ev_station_outlined,
  'face': Icons.face_outlined,
  'favorite': Icons.favorite_outline,
  'fireplace': Icons.fireplace_outlined,
  'flight_takeoff': Icons.flight_takeoff_outlined,
  'forest': Icons.forest_outlined,
  'games': Icons.games_outlined,
  'garden': Icons.yard_outlined,
  'handyman': Icons.handyman_outlined,
  'headphones': Icons.headphones_outlined,
  'home_work': Icons.home_work_outlined,
  'hotel': Icons.hotel_outlined,
  'house': Icons.house_outlined,
  'icecream': Icons.icecream_outlined,
  'keyboard': Icons.keyboard_outlined,
  'laptop': Icons.laptop_outlined,
  'lightbulb': Icons.lightbulb_outline,
  'liquor': Icons.liquor_outlined,
  'local_bar': Icons.local_bar_outlined,
  'local_cafe': Icons.local_cafe_outlined,
  'local_florist': Icons.local_florist_outlined,
  'local_gas_station': Icons.local_gas_station_outlined,
  'local_grocery_store': Icons.local_grocery_store_outlined,
  'local_laundry_service': Icons.local_laundry_service_outlined,
  'local_movies': Icons.local_movies_outlined,
  'local_pizza': Icons.local_pizza_outlined,
  'local_shipping': Icons.local_shipping_outlined,
  'menu_book': Icons.menu_book_outlined,
  'microwave': Icons.microwave_outlined,
  'music_note': Icons.music_note_outlined,
  'palette': Icons.palette_outlined,
  'payments': Icons.payments_outlined,
  'pedal_bike': Icons.pedal_bike_outlined,
  'percent': Icons.percent_outlined,
  'person': Icons.person_outline,
  'phone_iphone': Icons.phone_iphone_outlined,
  'receipt_long': Icons.receipt_long_outlined,
  'restaurant_menu': Icons.restaurant_menu_outlined,
  'science': Icons.science_outlined,
  'self_improvement': Icons.self_improvement_outlined,
  'shopping_bag': Icons.shopping_bag_outlined,
  'spa': Icons.spa_outlined,
  'sports_bar': Icons.sports_bar_outlined,
  'sports_esports': Icons.sports_esports_outlined,
  'storefront': Icons.storefront_outlined,
  'theaters': Icons.theaters_outlined,
  'train': Icons.train_outlined,
  'volunteer_activism': Icons.volunteer_activism_outlined,
  'wallet': Icons.account_balance_wallet_outlined,
  'wifi': Icons.wifi_outlined,
  // Reserved ledger-transfer category (ensureLedgerTransferCategory).
  'swap_horiz': Icons.swap_horiz_outlined,
};

Iterable<String> get kOnboardingIconKeys => kOnboardingCategoryIconMap.keys;

IconData onboardingIconForKey(String key) =>
    kOnboardingCategoryIconMap[key] ?? Icons.label_outline;
