import 'package:flutter/material.dart';

/// (EN, ES) label pair for an icon key.
@immutable
class OnboardingIconLabel {
  const OnboardingIconLabel(this.en, this.es);
  final String en;
  final String es;
}

/// Labels for **account** icon keys.
///
/// Keep in sync with [kOnboardingAccountIconMap]; unknown keys fall back to the icon key.
const Map<String, OnboardingIconLabel> kOnboardingAccountIconLabels = {
  'account_balance': OnboardingIconLabel('Bank', 'Banco'),
  'savings': OnboardingIconLabel('Savings', 'Ahorros'),
  'investment': OnboardingIconLabel('Investment', 'Inversión'),
  'credit_card': OnboardingIconLabel('Credit card', 'Tarjeta de crédito'),
  'loan': OnboardingIconLabel('Loan', 'Préstamo'),
  'mortgage': OnboardingIconLabel('Mortgage', 'Hipoteca'),
  'wallet': OnboardingIconLabel('Wallet', 'Cartera'),
  'payments': OnboardingIconLabel('Cash', 'Efectivo'),
  'store': OnboardingIconLabel('Store', 'Tienda'),
  'currency': OnboardingIconLabel('Currency exchange', 'Cambio de divisas'),
  'atm': OnboardingIconLabel('ATM', 'Cajero automático'),
  'account_tree': OnboardingIconLabel('Account tree', 'Árbol de cuentas'),
  'analytics': OnboardingIconLabel('Analytics', 'Analíticas'),
  'attach_money': OnboardingIconLabel('Money', 'Dinero'),
  'bank': OnboardingIconLabel('Bank', 'Banco'),
  'bar_chart': OnboardingIconLabel('Bar chart', 'Gráfico de barras'),
  'bolt': OnboardingIconLabel('Bolt', 'Rayo'),
  'business': OnboardingIconLabel('Business', 'Negocio'),
  'cafe': OnboardingIconLabel('Cafe', 'Café'),
  'car': OnboardingIconLabel('Car', 'Auto'),
  'card_giftcard': OnboardingIconLabel('Gift card', 'Tarjeta de regalo'),
  'construction': OnboardingIconLabel('Construction', 'Construcción'),
  'description': OnboardingIconLabel('Document', 'Documento'),
  'diamond': OnboardingIconLabel('Diamond', 'Diamante'),
  'eco': OnboardingIconLabel('Eco', 'Eco'),
  'electric_bolt': OnboardingIconLabel('Electricity', 'Electricidad'),
  'emoji_events': OnboardingIconLabel('Trophy', 'Trofeo'),
  'euro': OnboardingIconLabel('Euro', 'Euro'),
  'family_restroom': OnboardingIconLabel('Family', 'Familia'),
  'flight': OnboardingIconLabel('Flight', 'Vuelo'),
  'gavel': OnboardingIconLabel('Legal', 'Legal'),
  'handshake': OnboardingIconLabel('Handshake', 'Acuerdo'),
  'health_and_safety': OnboardingIconLabel('Health', 'Salud'),
  'home': OnboardingIconLabel('Home', 'Hogar'),
  'hotel': OnboardingIconLabel('Hotel', 'Hotel'),
  'house': OnboardingIconLabel('House', 'Casa'),
  'local_gas_station': OnboardingIconLabel('Gas station', 'Gasolinera'),
  'local_hospital': OnboardingIconLabel('Hospital', 'Hospital'),
  'local_mall': OnboardingIconLabel('Mall', 'Centro comercial'),
  'local_parking': OnboardingIconLabel('Parking', 'Estacionamiento'),
  'local_shipping': OnboardingIconLabel('Shipping', 'Envío'),
  'medical_services': OnboardingIconLabel('Medical', 'Médico'),
  'monetization_on': OnboardingIconLabel('Coin', 'Moneda'),
  'money': OnboardingIconLabel('Cash', 'Efectivo'),
  'pedal_bike': OnboardingIconLabel('Bicycle', 'Bicicleta'),
  'percent': OnboardingIconLabel('Percent', 'Porcentaje'),
  'person': OnboardingIconLabel('Person', 'Persona'),
  'phone_android': OnboardingIconLabel('Phone', 'Teléfono'),
  'pie_chart': OnboardingIconLabel('Pie chart', 'Gráfico circular'),
  'point_of_sale': OnboardingIconLabel('Point of sale', 'Punto de venta'),
  'public': OnboardingIconLabel('Global', 'Global'),
  'real_estate_agent': OnboardingIconLabel('Real estate', 'Bienes raíces'),
  'restaurant': OnboardingIconLabel('Restaurant', 'Restaurante'),
  'school': OnboardingIconLabel('School', 'Escuela'),
  'sports_soccer': OnboardingIconLabel('Sports', 'Deportes'),
  'shopping_bag': OnboardingIconLabel('Shopping bag', 'Bolsa de compras'),
  'shopping_cart': OnboardingIconLabel('Shopping cart', 'Carrito de compras'),
  'star': OnboardingIconLabel('Star', 'Estrella'),
  'subway': OnboardingIconLabel('Subway', 'Metro'),
  'train': OnboardingIconLabel('Train', 'Tren'),
  'volunteer_activism': OnboardingIconLabel('Volunteer', 'Voluntariado'),
  'work': OnboardingIconLabel('Work', 'Trabajo'),
};

/// Labels for **category** icon keys.
const Map<String, OnboardingIconLabel> kOnboardingCategoryIconLabels = {
  'lock': OnboardingIconLabel('Fixed expenses', 'Gastos fijos'),
  'savings': OnboardingIconLabel('Savings', 'Ahorros'),
  'home': OnboardingIconLabel('Home', 'Hogar'),
  'work': OnboardingIconLabel('Work', 'Trabajo'),
  'restaurant': OnboardingIconLabel('Restaurant', 'Restaurante'),
  'directions_car': OnboardingIconLabel('Car', 'Auto'),
  'shopping_cart': OnboardingIconLabel('Groceries', 'Despensa'),
  'movie': OnboardingIconLabel('Movies', 'Películas'),
  'fitness': OnboardingIconLabel('Fitness', 'Gimnasio'),
  'pets_outline': OnboardingIconLabel('Pets', 'Mascotas'),
  'school': OnboardingIconLabel('School', 'Escuela'),
  'local_hospital': OnboardingIconLabel('Hospital', 'Hospital'),
  'flight': OnboardingIconLabel('Flight', 'Vuelo'),
  'category': OnboardingIconLabel('Other', 'Otro'),
  'account_balance': OnboardingIconLabel('Bank', 'Banco'),
  'attach_money': OnboardingIconLabel('Money', 'Dinero'),
  'bakery_dining': OnboardingIconLabel('Bakery', 'Panadería'),
  'beach_access': OnboardingIconLabel('Beach', 'Playa'),
  'bolt': OnboardingIconLabel('Bolt', 'Rayo'),
  'brush': OnboardingIconLabel('Art', 'Arte'),
  'build': OnboardingIconLabel('Repairs', 'Reparaciones'),
  'cake': OnboardingIconLabel('Cake', 'Pastel'),
  'call': OnboardingIconLabel('Phone call', 'Llamada'),
  'camera': OnboardingIconLabel('Camera', 'Cámara'),
  'card_giftcard': OnboardingIconLabel('Gift card', 'Tarjeta de regalo'),
  'celebration': OnboardingIconLabel('Celebration', 'Celebración'),
  'chair': OnboardingIconLabel('Furniture', 'Muebles'),
  'child_care': OnboardingIconLabel('Child care', 'Cuidado infantil'),
  'cleaning_services': OnboardingIconLabel('Cleaning', 'Limpieza'),
  'coffee': OnboardingIconLabel('Coffee', 'Café'),
  'computer': OnboardingIconLabel('Computer', 'Computadora'),
  'credit_card': OnboardingIconLabel('Credit card', 'Tarjeta de crédito'),
  'diamond': OnboardingIconLabel('Jewelry', 'Joyería'),
  'directions_bus': OnboardingIconLabel('Bus', 'Autobús'),
  'dry_cleaning': OnboardingIconLabel('Dry cleaning', 'Tintorería'),
  'electric_bolt': OnboardingIconLabel('Electricity', 'Electricidad'),
  'emoji_events': OnboardingIconLabel('Trophy', 'Trofeo'),
  'emoji_food_beverage': OnboardingIconLabel('Tea', 'Té'),
  'ev_station': OnboardingIconLabel('EV station', 'Carga eléctrica'),
  'face': OnboardingIconLabel('Personal care', 'Cuidado personal'),
  'favorite': OnboardingIconLabel('Favorite', 'Favorito'),
  'fireplace': OnboardingIconLabel('Heating', 'Calefacción'),
  'flight_takeoff': OnboardingIconLabel('Travel', 'Viaje'),
  'forest': OnboardingIconLabel('Nature', 'Naturaleza'),
  'games': OnboardingIconLabel('Games', 'Juegos'),
  'garden': OnboardingIconLabel('Garden', 'Jardín'),
  'handyman': OnboardingIconLabel('Handyman', 'Reparaciones'),
  'headphones': OnboardingIconLabel('Headphones', 'Audífonos'),
  'home_work': OnboardingIconLabel('Home office', 'Oficina en casa'),
  'hotel': OnboardingIconLabel('Hotel', 'Hotel'),
  'house': OnboardingIconLabel('House', 'Casa'),
  'icecream': OnboardingIconLabel('Ice cream', 'Helado'),
  'keyboard': OnboardingIconLabel('Keyboard', 'Teclado'),
  'laptop': OnboardingIconLabel('Laptop', 'Laptop'),
  'lightbulb': OnboardingIconLabel('Utilities', 'Servicios'),
  'liquor': OnboardingIconLabel('Liquor', 'Licor'),
  'local_bar': OnboardingIconLabel('Bar', 'Bar'),
  'local_cafe': OnboardingIconLabel('Cafe', 'Café'),
  'local_florist': OnboardingIconLabel('Flowers', 'Flores'),
  'local_gas_station': OnboardingIconLabel('Gas', 'Gasolina'),
  'local_grocery_store': OnboardingIconLabel('Grocery store', 'Supermercado'),
  'local_laundry_service': OnboardingIconLabel('Laundry', 'Lavandería'),
  'local_movies': OnboardingIconLabel('Cinema', 'Cine'),
  'local_pizza': OnboardingIconLabel('Pizza', 'Pizza'),
  'local_shipping': OnboardingIconLabel('Shipping', 'Envío'),
  'menu_book': OnboardingIconLabel('Books', 'Libros'),
  'microwave': OnboardingIconLabel('Kitchen', 'Cocina'),
  'music_note': OnboardingIconLabel('Music', 'Música'),
  'palette': OnboardingIconLabel('Hobbies', 'Pasatiempos'),
  'payments': OnboardingIconLabel('Payments', 'Pagos'),
  'pedal_bike': OnboardingIconLabel('Bicycle', 'Bicicleta'),
  'percent': OnboardingIconLabel('Taxes', 'Impuestos'),
  'person': OnboardingIconLabel('Personal', 'Personal'),
  'phone_iphone': OnboardingIconLabel('Phone', 'Teléfono'),
  'receipt_long': OnboardingIconLabel('Bills', 'Recibos'),
  'restaurant_menu': OnboardingIconLabel('Dining out', 'Comer fuera'),
  'science': OnboardingIconLabel('Science', 'Ciencia'),
  'self_improvement': OnboardingIconLabel('Wellness', 'Bienestar'),
  'shopping_bag': OnboardingIconLabel('Shopping', 'Compras'),
  'spa': OnboardingIconLabel('Spa', 'Spa'),
  'sports_bar': OnboardingIconLabel('Sports bar', 'Bar deportivo'),
  'sports_esports': OnboardingIconLabel('Video games', 'Videojuegos'),
  'storefront': OnboardingIconLabel('Store', 'Tienda'),
  'theaters': OnboardingIconLabel('Theater', 'Teatro'),
  'train': OnboardingIconLabel('Train', 'Tren'),
  'volunteer_activism': OnboardingIconLabel('Donation', 'Donación'),
  'wallet': OnboardingIconLabel('Wallet', 'Cartera'),
  'wifi': OnboardingIconLabel('Internet', 'Internet'),
};

String onboardingAccountIconLabel(String key, Locale locale) {
  final e = kOnboardingAccountIconLabels[key];
  if (e == null) return key;
  return locale.languageCode == 'es' ? e.es : e.en;
}

String onboardingCategoryIconLabel(String key, Locale locale) {
  final e = kOnboardingCategoryIconLabels[key];
  if (e == null) return key;
  return locale.languageCode == 'es' ? e.es : e.en;
}
