import 'package:flutter/material.dart';

import '../domain/onboarding_models.dart';

/// Material icon keys the user can assign to an account (independent of account type).
final Map<String, IconData> kOnboardingAccountIconMap = <String, IconData>{
  'account_balance': Icons.account_balance_outlined,
  'savings': Icons.savings_outlined,
  'investment': Icons.trending_up_outlined,
  'credit_card': Icons.credit_card_outlined,
  'loan': Icons.receipt_long_outlined,
  'mortgage': Icons.home_work_outlined,
  'wallet': Icons.account_balance_wallet_outlined,
  'payments': Icons.payments_outlined,
  'store': Icons.storefront_outlined,
  'currency': Icons.currency_exchange_outlined,
  'atm': Icons.atm_outlined,
  'account_tree': Icons.account_tree_outlined,
  'analytics': Icons.analytics_outlined,
  'attach_money': Icons.attach_money_outlined,
  'bank': Icons.account_balance_outlined,
  'bar_chart': Icons.bar_chart_outlined,
  'bolt': Icons.bolt_outlined,
  'business': Icons.business_outlined,
  'cafe': Icons.local_cafe_outlined,
  'car': Icons.directions_car_outlined,
  'card_giftcard': Icons.card_giftcard_outlined,
  'construction': Icons.construction_outlined,
  'description': Icons.description_outlined,
  'diamond': Icons.diamond_outlined,
  'eco': Icons.eco_outlined,
  'electric_bolt': Icons.electric_bolt_outlined,
  'emoji_events': Icons.emoji_events_outlined,
  'euro': Icons.euro_outlined,
  'family_restroom': Icons.family_restroom_outlined,
  'flight': Icons.flight_outlined,
  'gavel': Icons.gavel_outlined,
  'handshake': Icons.handshake_outlined,
  'health_and_safety': Icons.health_and_safety_outlined,
  'home': Icons.home_outlined,
  'hotel': Icons.hotel_outlined,
  'house': Icons.house_outlined,
  'local_gas_station': Icons.local_gas_station_outlined,
  'local_hospital': Icons.local_hospital_outlined,
  'local_mall': Icons.local_mall_outlined,
  'local_parking': Icons.local_parking_outlined,
  'local_shipping': Icons.local_shipping_outlined,
  'medical_services': Icons.medical_services_outlined,
  'monetization_on': Icons.monetization_on_outlined,
  'money': Icons.money_outlined,
  'pedal_bike': Icons.pedal_bike_outlined,
  'percent': Icons.percent_outlined,
  'person': Icons.person_outlined,
  'phone_android': Icons.phone_android_outlined,
  'pie_chart': Icons.pie_chart_outline_outlined,
  'point_of_sale': Icons.point_of_sale_outlined,
  'public': Icons.public_outlined,
  'real_estate_agent': Icons.real_estate_agent_outlined,
  'restaurant': Icons.restaurant_outlined,
  'school': Icons.school_outlined,
  'sports_soccer': Icons.sports_soccer_outlined,
  'shopping_bag': Icons.shopping_bag_outlined,
  'shopping_cart': Icons.shopping_cart_outlined,
  'star': Icons.star_outline,
  'subway': Icons.subway_outlined,
  'train': Icons.train_outlined,
  'volunteer_activism': Icons.volunteer_activism_outlined,
  'work': Icons.work_outline,
};

String defaultAccountIconKeyForType(OnboardingAccountType type) {
  return switch (type) {
    OnboardingAccountType.cash => 'payments',
    OnboardingAccountType.checking => 'account_balance',
    OnboardingAccountType.savings => 'savings',
    OnboardingAccountType.investment => 'investment',
    OnboardingAccountType.creditCard => 'credit_card',
    OnboardingAccountType.loan => 'loan',
    OnboardingAccountType.mortgage => 'mortgage',
  };
}

IconData onboardingAccountIconForKey(String key) =>
    kOnboardingAccountIconMap[key] ?? Icons.account_balance_outlined;
